//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyChain
    {
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public int ProductId { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public string CourierName { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
